# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9adc4c8d4b817aa428356631fe3cb64e9133797f709f7c82e07db0b1e16aa6c0de9c817bcef62a1fec8e09d6d251c3936d0000a73bd24a09b06fdf092d81cd9

test:
  secret_key_base: e7c65681c7cea8870ca39ef546bd50c6f52aab5d8aba92d7ffde036e9a80c91f825a1afebf758027c266372fc73f2443c576602df0fec848d1737492a4e8b535

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
